require('dotenv').config({
  path: process.env.NODE_ENV === 'test' ? '.env.test' : '.env'
});

const industries = [ // used to validate company input
    "Accounting",
    "Advertising",
    "Aerospace",
    "Agriculture",
    "Airlines",
    "Animation",
    "Apparel & Fashion",
    "Architecture",
    "Art & Design",
    "Automotive",
    "Banking",
    "Biotechnology",
    "Broadcasting",
    "Building Materials",
    "Business Supplies & Equipment",
    "Chemicals",
    "Civil Engineering",
    "Construction",
    "Consulting",
    "Consumer Electronics",
    "Consumer Goods",
    "Consumer Services",
    "Cosmetics",
    "Dairy",
    "Defense & Space",
    "Education",
    "E-learning",
    "Electrical & Electronic Manufacturing",
    "Energy",
    "Engineering",
    "Entertainment",
    "Environmental Services",
    "Events Services",
    "Facilities Services",
    "Financial Services",
    "Food & Beverage",
    "Food Production",
    "Fundraising",
    "Furniture",
    "Gambling & Casinos",
    "Glass, Ceramics & Concrete",
    "Government Administration",
    "Government Relations",
    "Graphic Design",
    "Health, Wellness & Fitness",
    "Higher Education",
    "Hospital & Health Care",
    "Hospitality",
    "Human Resources",
    "Import & Export",
    "Individual & Family Services",
    "Industrial Automation",
    "Information Services",
    "Information Technology & Services",
    "Insurance",
    "Interior Design",
    "Internet",
    "Investment Banking",
    "Investment Management",
    "Judiciary",
    "Law Enforcement",
    "Law Practice",
    "Legal Services",
    "Legislative Office",
    "Libraries",
    "Logistics & Supply Chain",
    "Luxury Goods & Jewelry",
    "Machinery",
    "Management Consulting",
    "Maritime",
    "Marketing & Advertising",
    "Market Research",
    "Mechanical or Industrial Engineering",
    "Media Production",
    "Medical Devices",
    "Medical Practice",
    "Mental Health Care",
    "Military",
    "Mining & Metals",
    "Motion Pictures & Film",
    "Museums & Institutions",
    "Music",
    "Nanotechnology",
    "Newspapers",
    "Non-Profit Organization Management",
    "Oil & Energy",
    "Online Media",
    "Outsourcing/Offshoring",
    "Package/Freight Delivery",
    "Packaging & Containers",
    "Paper & Forest Products",
    "Performing Arts",
    "Pharmaceuticals",
    "Philanthropy",
    "Photography",
    "Plastics",
    "Political Organization",
    "Primary/Secondary Education",
    "Printing",
    "Professional Training & Coaching",
    "Program Development",
    "Public Policy",
    "Public Relations & Communications",
    "Public Safety",
    "Publishing",
    "Railroad Manufacture",
    "Ranching",
    "Real Estate",
    "Recreational Facilities & Services",
    "Religious Institutions",
    "Renewables & Environment",
    "Research",
    "Restaurants",
    "Retail",
    "Security & Investigations",
    "Semiconductors",
    "Shipbuilding",
    "Sporting Goods",
    "Sports",
    "Staffing & Recruiting",
    "Supermarkets",
    "Telecommunications",
    "Textiles",
    "Think Tanks",
    "Tobacco",
    "Translation & Localization",
    "Transportation/Trucking/Railroad",
    "Utilities",
    "Venture Capital & Private Equity",
    "Veterinary",
    "Warehousing",
    "Wholesale",
    "Wine & Spirits",
    "Wireless",
    "Writing & Editing",
    "Other",
]

module.exports = {
  port:             process.env.PORT             || 3000,
  nodeEnv:          process.env.NODE_ENV         || 'development',
  db: {
    host:           process.env.DB_HOST          || 'localhost',
    port:           process.env.DB_PORT          || 5432,
    name:           process.env.DB_NAME,
    user:           process.env.DB_USER,
    password:       process.env.DB_PASSWORD,
  },
  jwt: {
    secret:         process.env.JWT_SECRET,
    refreshSecret:  process.env.JWT_REFRESH_SECRET,
    accessExpiry:   process.env.JWT_ACCESS_EXPIRY || '15m',
    refreshExpiry:  process.env.JWT_REFRESH_EXPIRY || '7d',
  },
  upload: {
    base_path:      process.env.UPLOAD_PATH || 'uploads'
  },
  industries
};